### ISSUE TITLE
undefined method `configuration' for RSpec:Module (NoMethodError)

### ISSUE THREAD

**Issue by Geesu** [rubyatscale/stimpack#12]
I've added packwerk and stimpack to our rails monolith but unfortunately if I start `bin/rails c` it fails with this exception:

```
bin/rails c
/Users/user/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/stimpack-0.4.0/lib/stimpack/integrations/rspec.rb:8:in `block in install': undefined method `configuration' for RSpec:Module (NoMethodError)
	from /Users/user/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/stimpack-0.4.0/lib/stimpack/packs.rb:36:in `each_value'
	from /Users/user/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/stimpack-0.4.0/lib/stimpack/packs.rb:36:in `each'
	from /Users/user/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/stimpack-0.4.0/lib/stimpack/integrations/rspec.rb:7:in `install'
	from /Users/user/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/stimpack-0.4.0/lib/stimpack.rb:22:in `load'
	from /Users/user/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/stimpack-0.4.0/lib/stimpack/railtie.rb:6:in `block in <class:Railtie>'
	from /Users/user/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/activesupport-6.1.6.1/lib/active_support/lazy_load_hooks.rb:68:in `block in execute_hook'
	from /Users/user/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/activesupport-6.1.6.1/lib/active_support/lazy_load_hooks.rb:61:in `with_execution_control'
	from /Users/user/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/activesupport-6.1.6.1/lib/active_support/lazy_load_hooks.rb:66:in `execute_hook'
	from /Users/user/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/activesupport-6.1.6.1/lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks'
	from /Users/user/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/activesupport-6.1.6.1/lib/active_support/lazy_load_hooks.rb:51:in `each'
	from /Users/user/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/activesupport-6.1.6.1/lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'
	from /Users/user/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/railties-6.1.6.1/lib/rails/application.rb:96:in `inherited'
	from /Users/user/Projects/app/app/config/application.rb:19:in `<module:Flowspace>'
	from /Users/user/Projects/app/app/config/application.rb:17:in `<top (required)>'
	from /Users/user/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/spring-2.1.1/lib/spring/application.rb:92:in `require'
	from /Users/user/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/spring-2.1.1/lib/spring/application.rb:92:in `preload'
	from /Users/user/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/spring-2.1.1/lib/spring/application.rb:157:in `serve'
	from /Users/user/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/spring-2.1.1/lib/spring/application.rb:145:in `block in run'
	from /Users/user/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/spring-2.1.1/lib/spring/application.rb:139:in `loop'
	from /Users/user/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/spring-2.1.1/lib/spring/application.rb:139:in `run'
	from /Users/user/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/spring-2.1.1/lib/spring/application/boot.rb:19:in `<top (required)>'
	from /Users/user/.rbenv/versions/2.7.5/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	from /Users/user/.rbenv/versions/2.7.5/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
```

I added a `binding.pry` right before this line to look at what is available for the `::RSpec` module and it's not much. I'm not sure why it is defined here:

```
[3] pry(Stimpack::Integrations::RSpec)> cd ::RSpec
[4] pry(RSpec):1> ls
constants: Rails
locals: _  __  _dir_  _ex_  _file_  _in_  _out_  pry_instance
```

When executing `$` it shows the module is defined here:

```
From: /Users/user/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/rspec-rails-5.1.2/lib/rspec/rails/feature_check.rb:1
Module name: RSpec
Number of monkeypatches: 2. Use the `-a` option to display all available monkeypatches
Number of lines: 47
```

Any ideas why this is occurring?

**Comment by Geesu** [comment]
I added this as a fix https://github.com/rubyatscale/stimpack/pull/13

**Comment by iMacTia** [comment]
Experiencing the same issue, I believe this can happen fairly easily if any of your dependencies extends `RSpec`
